# Generated by Django 3.0.4 on 2020-03-26 06:59

from django.db import migrations, models
import raven.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RavenFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now=True)),
                ('r_file', models.FileField(storage=raven.models.MediaFileSystemStorage(), upload_to='')),
                ('md256sum', models.CharField(max_length=36)),
            ],
        ),
    ]
