# Generated by Django 3.0.4 on 2020-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raven', '0002_ravenfiles_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravenfiles',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
