# Generated by Django 3.0.4 on 2020-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raven', '0003_auto_20200326_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravenfiles',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
